### PR TITLE
Fixes error with spaces in windows user names

### PR DESCRIPTION
**Pull request by Steveveepee**

### CODE REVIEW

**Comment by shdwp** [comment]
Wouldn't putting quotes around %UserProfile% suffice?

I.e. 

`py.exe __init__.py "%UserProfile%" ....`

I'd still like to save the opportunity of providing the path by the user himself if he runs into issues.

**Comment by Steveveepee** [comment]
Oh, hey, if that works :) 

The fix I pushed was only because that's the first one I found.

I'm not a python programmer, but it seems messy to pull stuff like that in from a batch file command line.

**Comment by shdwp** [comment]
I try to leave it as platform-independent as possible (sometimes I develop this on mac), so it does seem like a good intermediate fix, which would suffice path finding on windows and still provide easy way to override it by the user.

**Comment by shdwp** [comment]
You could provide the PR for start.bat with quotes if you want to, or I do it by myself in the next RC.

**Comment by shdwp** [comment]
Fixed now in develop branch.

**Pull request closed without merging**
