### PR TITLE
Scrollable & Zoomable Map view

### PR DESCRIPTION
**Pull request by Khopa**
Demo

I modified the current map overview implementation, so the map can be zoomed in, and moved around. 
To achieve this, i use pygame to render an SDL layer in the tk window.

The pygame/SDL code is a bit low level, but at least it gives way more freedom than the tkinter canvas.

### Map background : 
I changed the current background images for the maps, made them bigger so they can be zoomed in.

So the image does not look too bad when zoomed in, i applied a basic oil paint effect in paintDotNet on them to make them look a bit smoother.

### Strike targets : 

I display an icon for each category of strike target on their location on the map.
When the mouse hover over one, a tooltip is also displayed. A line is also drawn between the target and it's parent control point.

image

When a target has been dealt with, a green checkmark will replace the icon :

image

**Disclaimer :** I made these icons in 30 s, and yes, they could be much better. 😀🎨  

### Control Point's strength : 

I couldn't find a good way to display them in the same way it was done with arcs in tk with pygame.
So i changed it a bit so the half circle rendered appears smaller when the strength of a base is diminished : 

image

### Intel : 

When you hover over a control point, it will display the current units present there in the top left corner : 

image

### Declutter

To declutter the map view, i added a few checkboxes to control what to display : 

image

### Issues/Things i'm aware of 

* ~~The zoom is annoying to use.~~ (Still could be better)
* There is still content and text overlaping
* Ideally size of text should depend on zoom level
* ~~When you toggle a declutter option you have to move the mouse over the viewport to actually have it updated~~ (Fixed)
* Issue with frontline display in some case ?

### Pygame/Distribution

Well, pygame must be installed to be able to run this. 

```pip install pygame```

I'm unsure about the release/distribution of pygame. Not sure if pygame should be redistributed in the release or if the launcher should run pip install to retrieve the lib before launching the tk app.

### CODE REVIEW

**Comment by Khopa** [comment]
I also added a menu.

image

So it is now possible to start a new game from there without having to delete the save file.
So possibly related to #40 ?

There is a confirmation popup when you try to do so : 

image

*Note : Don't mind the "oui"/"non", tkinter use system language to display these, so it'll appear as yes/no on an english window.*

I also added a Help menu, with multiple links to the manual, troubleshoot guide, github.

image

When you click on one of the items, it'll open the corresponding url in system web browser.

**Comment by shdwp** [comment]
This is really cool. Do you plan on working on this further, or I could merge the PR?

**Comment by Khopa** [comment]
I think you can merge in it's current state if you're fine with it !

I may continue to work on it and improve it, but i'll do another PR then. 
If you have issues related to the map, ping me.

**Comment by calvinmorrow** [comment]
I love the map changes.  It makes the campaign really come to life and gives a nice sense of progress.

One issue I found while testing:  At lower resolutions (1440x900) the UI portion of the screen can get cut off, resulting in the inability to pass / end turn.  This isn't an issue at 1920x1080.  I only found it via a Remote Desktop connection that I had set to a smaller resolution.

liberation

**Comment by Khopa** [comment]
Yes, i've had this issue too in 1080p, when i had 6-7 bases from which to choose a mission from, then i couldn't select the last one. It can be really annoying.

The new map view size is currently hardcoded to 1066*600, which is a lot bigger than the previous one, and it's a lot if you don't run on 1080p.

So i just added a new button to collapse/expand the map : 

**Map reduced :** 

image

**Map expanded (default) :** 

image

Technically, the issue could still occur with the map reduced on a small enough screen.

**Comment by shdwp** [comment]
Yeah, this is really cool and would be a really good base for further improvements. I'll merge it into `develop` (please use that for further PRs)

**Pull request merged**
